# -*- coding: utf-8 -*-
"""productivity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQFh63pO_GxjDKy50YwJ78mwV4ePAl1L
"""

import pandas as pd
import matplotlib.pyplot as plt

# Sample DataFrame for illustration (replace this with your actual data)
data = {
    'leetcode': [3, 0],
    'research': [0,0],
    'gym': [1, 0],
    'healthy_eating': [1, 0],
    'applied_res_homework': [0,0],
    'histart_res_homework': [1, 0],
    'urban_homework': [0, 0],
    '198_homework': [0, 0],
    'ethics_homework': [0, 0]
}

df = pd.DataFrame(data)

# Plot each metric separately
for column in df.columns:
    plt.figure(figsize=(6, 4))
    plt.title(f'{column} Metric Over Time')

    # Set color to red if all values are zero, otherwise green
    color = 'red' if df[column].sum() == 0 else 'green'

    plt.plot(df.index, df[column], color=color, label=column, linewidth=2)
    plt.xlabel('Time')
    plt.ylabel('Score')
    plt.legend()
    plt.grid(True)
    plt.show()